# pull the official image
FROM python:3.8.3-slim-buster

# set worging directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc postgresql \
  && apt-get clean

# install python dependencies
COPY pyproject.toml poetry.lock ./
RUN pip install --upgrade pip \
  && pip install poetry \
  && poetry export -f requirements.txt > requirements.txt --dev --without-hashes \
  && pip install -r requirements.txt

# add app
COPY . .

# run entrypoint
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
